// 200記事の企画構成マスターリスト
// カテゴリ: career(転職), salary(年収), license(資格), job-type(職種), industry(業界), interview(体験談)
// 2026/1/1〜毎日1記事投稿

export interface ArticlePlan {
  slug: string
  title: string
  category: string
  tags: string[]
  excerpt: string
}

export const articlePlans: ArticlePlan[] = [
  // === 1月: 建設業界の基本と転職準備 ===
  { slug: "construction-industry-overview-2026", title: "建設業界の現状と将来性 — 2026年版", category: "industry", tags: ["業界動向","市場規模"], excerpt: "国内建設市場の規模推移と今後の見通しを解説。人手不足の実態とICT化の進展を踏まえた業界の将来性を分析します。" },
  { slug: "construction-job-types-guide", title: "建設業界の職種一覧 — 仕事内容・必要資格・年収まとめ", category: "job-type", tags: ["職種一覧","未経験"], excerpt: "建築・土木・設備・内装・解体など建設業界の主要職種を網羅。それぞれの仕事内容・必要資格・年収相場を紹介。" },
  { slug: "construction-career-change-first-step", title: "未経験から建設業界へ — 転職の最初の一歩", category: "career", tags: ["未経験","転職"], excerpt: "異業種から建設業界へ転職するためのステップを解説。求人の探し方から面接対策まで。" },
  { slug: "tobishoku-work-guide", title: "鳶職人の仕事内容 — 種類・1日の流れ・やりがい", category: "job-type", tags: ["鳶職","職種解説"], excerpt: "足場鳶・鉄骨鳶・重量鳶の違い、1日のスケジュール、仕事のやりがいと厳しさを現場目線で紹介。" },
  { slug: "construction-worker-salary-data", title: "建設作業員の平均年収は？職種別・年齢別データ", category: "salary", tags: ["年収","統計"], excerpt: "厚生労働省のデータをもとに建設作業員の平均年収を職種別・年齢別に分析。収入を上げるポイントも解説。" },
  { slug: "second-class-construction-management", title: "2級建築施工管理技士とは — 受験資格・試験内容・勉強法", category: "license", tags: ["施工管理技士","資格"], excerpt: "2級建築施工管理技士の受験資格、試験科目、合格率、おすすめの勉強方法を徹底解説。" },
  { slug: "type2-electrician-guide", title: "第二種電気工事士の取得ガイド — 筆記・実技の攻略法", category: "license", tags: ["電気工事士","国家資格"], excerpt: "第二種電気工事士の試験概要から効率的な勉強法、実技試験のコツまでを解説。" },
  { slug: "construction-resume-tips", title: "建設業界向け履歴書の書き方 — 採用担当が見るポイント", category: "career", tags: ["履歴書","面接対策"], excerpt: "建設会社の採用担当が重視する履歴書のポイント。職歴の書き方や資格欄の記載方法を具体例つきで解説。" },
  { slug: "civil-engineering-worker-guide", title: "土木作業員の仕事内容と1日の流れ", category: "job-type", tags: ["土木","職種解説"], excerpt: "道路・橋梁・トンネルなど土木工事の現場で働く作業員の仕事内容を詳しく紹介。" },
  { slug: "construction-interview-questions", title: "建設会社の面接でよく聞かれる質問と回答例", category: "career", tags: ["面接","転職"], excerpt: "建設業界特有の面接質問と好印象を与える回答例を紹介。体力面や安全意識に関する質問への対策も。" },
  { slug: "tamakake-license-guide", title: "玉掛け技能講習の取り方 — 費用・日数・試験内容", category: "license", tags: ["玉掛け","技能講習"], excerpt: "クレーン作業に必須の玉掛け技能講習。申込みから修了までの流れ、費用、試験内容を解説。" },
  { slug: "construction-work-clothes", title: "建設現場の作業着・装備ガイド — 必須アイテム一覧", category: "industry", tags: ["装備","安全"], excerpt: "ヘルメット・安全帯・作業靴など建設現場で必要な装備品を紹介。選び方のポイントと費用の目安。" },
  { slug: "sekokan-vs-genba-worker", title: "施工管理と現場作業員の違い — 仕事内容・年収・キャリア", category: "job-type", tags: ["施工管理","比較"], excerpt: "施工管理技士と現場作業員の役割の違い、年収差、キャリアパスを比較。どちらが自分に合うか判断する材料に。" },
  { slug: "construction-salary-up-methods", title: "建設業で年収を上げる5つの方法", category: "salary", tags: ["年収アップ","キャリア"], excerpt: "資格取得・転職・独立など、建設業界で収入を上げるための具体的な5つの方法を紹介。" },
  { slug: "ashiba-license-guide", title: "足場の組立て等作業主任者とは — 取得方法と役割", category: "license", tags: ["足場","資格"], excerpt: "足場の組立て等作業主任者の技能講習の概要、受講資格、現場での役割を解説。" },
  { slug: "construction-safety-basics", title: "建設現場の安全対策 — 新人が知っておくべき基本", category: "industry", tags: ["安全","新人向け"], excerpt: "KY活動・保護具の使い方・高所作業の注意点など、新人作業員が知っておくべき安全の基本。" },
  { slug: "interview-tobi-career", title: "飲食業から鳶職人へ — 転職3年目のリアル", category: "interview", tags: ["鳶職","転職体験"], excerpt: "飲食店から鳶職に転職した32歳男性のリアルな体験談。きっかけ、苦労した点、現在の年収を語ります。" },
  { slug: "heavy-equipment-operator-guide", title: "重機オペレーターの仕事内容 — 必要な免許と年収", category: "job-type", tags: ["重機","オペレーター"], excerpt: "バックホウ・ブルドーザーなど重機オペレーターの仕事内容、必要な免許、年収相場を解説。" },
  { slug: "construction-bonus-reality", title: "建設業界のボーナス事情 — 支給額と時期", category: "salary", tags: ["ボーナス","待遇"], excerpt: "建設会社のボーナスはいくら？大手ゼネコンから中小企業まで、支給額の実態と時期を調査。" },
  { slug: "first-class-construction-management", title: "1級建築施工管理技士の難易度と勉強法", category: "license", tags: ["施工管理技士","1級"], excerpt: "1級建築施工管理技士の合格率・難易度・必要な勉強時間、おすすめの参考書を紹介。" },
  { slug: "construction-women-guide", title: "建設業界で働く女性 — 職種・環境・キャリアパス", category: "industry", tags: ["女性","ダイバーシティ"], excerpt: "建設現場で活躍する女性が増加中。女性が活躍できる職種や職場環境の実態を紹介。" },
  { slug: "construction-overtime-reality", title: "建設業界の残業時間 — 2024年規制後の変化", category: "industry", tags: ["残業","働き方改革"], excerpt: "2024年の残業上限規制後、建設業界の働き方はどう変わったか。現場のリアルな声を紹介。" },
  { slug: "plumber-work-guide", title: "配管工の仕事内容と将来性 — 水道・ガス・空調", category: "job-type", tags: ["配管工","職種解説"], excerpt: "配管工の種類（水道・ガス・空調）ごとの仕事内容、必要な資格、年収、将来性を解説。" },
  { slug: "construction-age-limit", title: "建設業は何歳まで働ける？年齢別のキャリア設計", category: "career", tags: ["年齢","キャリア"], excerpt: "20代・30代・40代・50代それぞれの建設業界でのキャリア設計と、体力面での対策を解説。" },
  { slug: "vehicle-construction-machine-license", title: "車両系建設機械の運転資格 — 種類と取得方法", category: "license", tags: ["重機","資格"], excerpt: "車両系建設機械運転技能講習と特別教育の違い、対象機械、取得費用を解説。" },
  { slug: "construction-apprentice-salary", title: "建設業界の見習い期間 — 給与・期間・成長ステップ", category: "salary", tags: ["見習い","新人"], excerpt: "建設業界での見習い期間の長さ、その間の給与水準、一人前になるまでの成長ステップを紹介。" },
  { slug: "interview-factory-to-electrician", title: "工場勤務から電気工事士へ — 資格で切り開いた転職", category: "interview", tags: ["電気工事士","転職体験"], excerpt: "工場作業員から電気工事士に転職した28歳男性の体験談。資格取得の経緯と現在の仕事について。" },
  { slug: "demolition-work-guide", title: "解体工事の仕事内容 — 需要拡大中の注目職種", category: "job-type", tags: ["解体","職種解説"], excerpt: "老朽化建物の増加で需要が伸びる解体工事。仕事の流れ、必要な資格、年収を詳しく解説。" },
  { slug: "construction-health-check", title: "建設作業員の健康管理 — 体力維持と怪我の予防", category: "industry", tags: ["健康","安全"], excerpt: "建設現場で長く働くための体力づくり、腰痛予防、熱中症対策など健康管理のポイント。" },
  { slug: "sekokan-salary-data-2026", title: "施工管理技士の年収データ — 1級と2級の差は？", category: "salary", tags: ["施工管理","年収"], excerpt: "施工管理技士の年収を1級・2級、建築・土木別に比較。年収を上げるためのキャリアパスも紹介。" },
  { slug: "construction-career-path-map", title: "建設業界のキャリアパス全体像 — 10年後の自分を描く", category: "career", tags: ["キャリア","将来設計"], excerpt: "作業員→職長→施工管理→独立。建設業界でのキャリアパスの全体像と、各ステージで必要なスキル・資格。" },

  // === 2月: 資格特集月間 ===
  { slug: "crane-operator-license", title: "クレーン運転士の資格取得ガイド — 種類と費用", category: "license", tags: ["クレーン","資格"], excerpt: "移動式クレーン・小型移動式クレーンなど、クレーン関連の資格の種類と取得方法を解説。" },
  { slug: "first-class-civil-management", title: "1級土木施工管理技士の攻略法 — 合格者の勉強法", category: "license", tags: ["土木","施工管理技士"], excerpt: "1級土木施工管理技士の試験概要と合格した人の具体的な勉強スケジュール・使用教材を紹介。" },
  { slug: "architecture-license-comparison", title: "建築士と施工管理技士の違い — どちらを目指すべきか", category: "license", tags: ["建築士","比較"], excerpt: "建築士と施工管理技士の役割・受験資格・年収の違いを比較。自分に合ったキャリアの選び方。" },
  { slug: "interior-finishing-jobs", title: "内装仕上げ工事の職種 — クロス・床・塗装の仕事と年収", category: "job-type", tags: ["内装","職種解説"], excerpt: "クロス職人・床仕上げ・塗装工の仕事内容と年収を比較。未経験から始める方法も紹介。" },
  { slug: "construction-holidays-reality", title: "建設業界の休日事情 — 週休2日は本当に増えた？", category: "industry", tags: ["休日","働き方"], excerpt: "4週8休推進の現状。実際の現場ではどの程度休めるのか、企業規模別のデータを紹介。" },
  { slug: "welding-license-guide", title: "溶接の資格一覧 — アーク溶接からJIS資格まで", category: "license", tags: ["溶接","資格"], excerpt: "アーク溶接特別教育、ガス溶接技能講習、JIS溶接技能者など溶接関連の資格を網羅解説。" },
  { slug: "construction-job-search-tips", title: "建設業界の求人の探し方 — 専門サイトの活用法", category: "career", tags: ["求人","転職"], excerpt: "ハローワーク・専門求人サイト・知人紹介。建設業界での求人の探し方と各方法のメリット・デメリット。" },
  { slug: "rebar-worker-guide", title: "鉄筋工の仕事と年収 — 需要の高い専門職", category: "job-type", tags: ["鉄筋","職種解説"], excerpt: "鉄筋工の仕事内容、必要な資格（鉄筋施工技能士）、年収の推移を現場経験者の視点で解説。" },
  { slug: "construction-retirement-age", title: "建設業界の定年と退職金 — 老後の備え", category: "salary", tags: ["退職金","定年"], excerpt: "建設会社の定年年齢、退職金の相場、再雇用制度の実態を大手から中小まで調査。" },
  { slug: "oxygen-deficiency-license", title: "酸欠作業主任者の資格 — 取得方法と現場での重要性", category: "license", tags: ["酸欠","安全資格"], excerpt: "酸素欠乏・硫化水素危険作業主任者の技能講習。どんな現場で必要か、取得の流れを解説。" },
  { slug: "interview-sales-to-sekokan", title: "営業職から施工管理へ — コミュニケーション力が活きた転職", category: "interview", tags: ["施工管理","転職体験"], excerpt: "営業職から施工管理技士に転職した35歳の体験談。前職のスキルがどう活きたかを語る。" },
  { slug: "construction-company-size-comparison", title: "大手ゼネコンと中小建設会社の違い — 給与・環境・成長", category: "industry", tags: ["企業規模","比較"], excerpt: "大手と中小の建設会社を年収・福利厚生・仕事内容・成長速度で比較。自分に合う規模は？" },
  { slug: "forklift-license-guide", title: "フォークリフト運転技能講習 — 取得の流れと活用場面", category: "license", tags: ["フォークリフト","資格"], excerpt: "フォークリフト運転技能講習の受講資格、費用、日数。建設現場での活用場面を紹介。" },
  { slug: "painting-work-guide", title: "塗装工の仕事内容 — 建築塗装と土木塗装の違い", category: "job-type", tags: ["塗装","職種解説"], excerpt: "建築塗装と土木塗装（橋梁等）の違い、仕事の流れ、年収、独立の可能性を解説。" },
  { slug: "construction-social-insurance", title: "建設業界の社会保険 — 加入義務と確認ポイント", category: "industry", tags: ["社会保険","労働環境"], excerpt: "建設業界での社会保険加入の義務化。入社前に確認すべきポイントと一人親方の保険事情。" },
  { slug: "surveyor-license-guide", title: "測量士・測量士補の資格 — 取得方法と年収", category: "license", tags: ["測量","資格"], excerpt: "測量士と測量士補の違い、試験の概要、取得後のキャリアと年収の目安を解説。" },
  { slug: "construction-apprenticeship-reality", title: "建設業界の徒弟制度は今も残る？ — 教育体制の変化", category: "industry", tags: ["教育","人材育成"], excerpt: "かつての徒弟制度から現代の教育体制へ。建設業界の人材育成方法の変遷と現状。" },
  { slug: "construction-salary-by-region", title: "建設業界の年収 — 地域別ランキング", category: "salary", tags: ["年収","地域差"], excerpt: "東京・大阪・名古屋など主要都市と地方の建設作業員の年収差をデータで比較。" },

  // === 3月: 転職シーズン特集 ===
  { slug: "construction-spring-recruitment", title: "建設業界の春採用 — 4月入社に向けた転職活動の進め方", category: "career", tags: ["春採用","転職"], excerpt: "4月入社を目指す建設業界の転職スケジュール。3月からでも間に合う求人の探し方。" },
  { slug: "second-class-civil-management", title: "2級土木施工管理技士の受験対策まとめ", category: "license", tags: ["土木","施工管理技士"], excerpt: "2級土木施工管理技士の受験資格、試験内容、過去問の活用法をまとめて解説。" },
  { slug: "carpenter-work-guide", title: "大工の仕事内容 — 伝統技術とこれからの需要", category: "job-type", tags: ["大工","職種解説"], excerpt: "大工の種類（造作大工・型枠大工等）、仕事内容、年収、木造住宅の需要見通しを解説。" },
  { slug: "construction-vacation-tips", title: "建設業界で有給を取るコツ — 現場の暗黙ルール", category: "industry", tags: ["有給","働き方"], excerpt: "建設現場で有給休暇を取りやすくするためのポイント。閑散期の活用や事前調整の方法。" },
  { slug: "construction-night-work", title: "建設業の夜勤 — 手当・体調管理・対象工事", category: "salary", tags: ["夜勤","手当"], excerpt: "夜間工事の種類、夜勤手当の相場、体調管理のコツを現場経験者が解説。" },
  { slug: "scaffold-work-guide", title: "足場職人の仕事と資格 — 年収と将来性", category: "job-type", tags: ["足場","職種解説"], excerpt: "足場の組立て解体作業の仕事内容、必要な資格、年収相場、需要の見通しを紹介。" },
  { slug: "construction-mental-health", title: "建設現場のメンタルヘルス — ストレス対策と相談窓口", category: "industry", tags: ["メンタルヘルス","健康"], excerpt: "建設業界特有のストレス要因と、メンタルヘルスケアの方法、利用できる相談窓口を紹介。" },
  { slug: "type1-electrician-guide", title: "第一種電気工事士の難易度と年収アップ効果", category: "license", tags: ["電気工事士","1種"], excerpt: "第一種電気工事士の試験概要、合格率、取得後の年収変化。第二種との実務範囲の違いも解説。" },
  { slug: "interview-driver-to-dokata", title: "トラック運転手から土木作業員へ — 40代の転職記", category: "interview", tags: ["土木","転職体験"], excerpt: "長距離ドライバーから土木作業員に転職した42歳の体験談。体力面の不安と克服の過程。" },
  { slug: "construction-tool-basics", title: "建設現場の基本工具 — 新人が最初に覚えるべき道具", category: "industry", tags: ["工具","新人向け"], excerpt: "インパクトドライバー・水平器・差し金など、建設現場で最初に覚えるべき基本工具を写真付きで紹介。" },
  { slug: "left-hand-worker-guide", title: "左官工の仕事内容と年収 — 手に職をつける伝統技術", category: "job-type", tags: ["左官","職種解説"], excerpt: "左官工の仕事内容、技術の習得に必要な期間、年収相場、独立の可能性を解説。" },
  { slug: "construction-commute-tips", title: "建設現場への通勤事情 — 直行直帰と集合場所", category: "industry", tags: ["通勤","働き方"], excerpt: "建設現場への通勤方法。直行直帰のルール、車通勤の可否、集合場所からの移動について。" },

  // === 3月後半: 転職応援 ===
  { slug: "construction-job-offer-comparison", title: "建設会社の内定を比較する方法 — 給与以外の見るべき点", category: "career", tags: ["内定","比較"], excerpt: "複数の内定をもらったとき、給与・福利厚生・現場環境のどこを比較すべきか解説。" },
  { slug: "ground-improvement-work", title: "地盤改良工事の仕事内容と必要な資格", category: "job-type", tags: ["地盤改良","土木"], excerpt: "柱状改良・表層改良・杭工事など地盤改良の種類と、従事するために必要な資格を紹介。" },
  { slug: "construction-salary-negotiation", title: "建設業界の給与交渉術 — 面接で年収を上げるコツ", category: "salary", tags: ["給与交渉","面接"], excerpt: "建設会社の面接で給与交渉をする際のタイミングと伝え方。資格や経験の効果的なアピール法。" },
  { slug: "fire-protection-engineer", title: "消防設備士の資格 — 甲種・乙種の違いと取得方法", category: "license", tags: ["消防設備士","資格"], excerpt: "消防設備士の甲種と乙種の違い、試験内容、建設業界での活用場面を解説。" },
  { slug: "interview-newgrad-construction", title: "高校卒業後すぐ建設業界へ — 20歳の現場職人の話", category: "interview", tags: ["新卒","体験談"], excerpt: "高校卒業後に建設会社に入社した20歳の職人が語る、現場の日常と成長の実感。" },
  { slug: "construction-union-guide", title: "建設業の組合と労働組合 — 加入のメリット", category: "industry", tags: ["労働組合","権利"], excerpt: "建設業界の労働組合の種類と加入メリット。共済制度や退職金制度について。" },
  { slug: "waterproofing-work-guide", title: "防水工の仕事と年収 — 雨漏り修繕から新築まで", category: "job-type", tags: ["防水","職種解説"], excerpt: "防水工の仕事内容、シート防水・ウレタン防水の違い、年収、将来性を解説。" },
  { slug: "construction-tax-guide", title: "建設作業員の確定申告 — 一人親方と会社員の違い", category: "salary", tags: ["確定申告","税金"], excerpt: "一人親方の確定申告の基本と、会社員との税金の違い。経費にできるものリスト。" },

  // === 4月: 新生活・新人向け ===
  { slug: "construction-first-day", title: "建設現場の初日 — 新人が準備すべきこと", category: "career", tags: ["新人","入社準備"], excerpt: "建設会社に入社した初日の流れ。持ち物・服装・挨拶の仕方から現場ルールまで。" },
  { slug: "construction-terminology-50", title: "建設現場の専門用語50選 — 新人向け", category: "industry", tags: ["用語","新人向け"], excerpt: "建設現場でよく使われる専門用語50個をカテゴリ別に解説。これだけ覚えれば現場で困らない。" },
  { slug: "concrete-work-basics", title: "コンクリート工事の基本 — 打設・養生・検査の流れ", category: "job-type", tags: ["コンクリート","基礎知識"], excerpt: "コンクリート工事の一連の流れ。打設準備から養生期間、強度試験まで現場の基本を解説。" },
  { slug: "construction-mentor-system", title: "建設現場のOJT制度 — 先輩から学ぶ技術習得", category: "industry", tags: ["OJT","人材育成"], excerpt: "建設業界のOJT（現場教育）の実態。技術を効率よく学ぶためのポイント。" },
  { slug: "plaster-board-installer-guide", title: "ボード工の仕事内容と年収 — 内装工事の要", category: "job-type", tags: ["ボード工","内装"], excerpt: "石膏ボードの施工を行うボード工の仕事内容、必要な技術、年収の目安を紹介。" },
  { slug: "construction-new-employee-salary", title: "建設業界の初任給 — 高卒と大卒でどう違う？", category: "salary", tags: ["初任給","新卒"], excerpt: "建設会社の初任給を高卒・大卒・職種別に比較。入社1年目の手取り額の実態。" },
  { slug: "construction-license-priority", title: "建設業界で最初に取るべき資格5選", category: "license", tags: ["資格","新人向け"], excerpt: "入社1〜2年目で取得を目指すべき資格を優先度順に紹介。費用と日数の目安つき。" },
  { slug: "interview-woman-sekokan", title: "女性施工管理技士のリアル — 現場での苦労と手応え", category: "interview", tags: ["女性","施工管理"], excerpt: "建築施工管理技士として働く30代女性のインタビュー。現場での苦労と働きがい。" },
  { slug: "construction-smartphone-apps", title: "建設現場で使えるスマホアプリ10選", category: "industry", tags: ["アプリ","ICT"], excerpt: "施工管理・図面閲覧・写真管理など、現場で役立つスマートフォンアプリを厳選紹介。" },
  { slug: "pipe-fitter-salary", title: "管工事作業員の年収 — 配管・空調・ガスの比較", category: "salary", tags: ["管工事","年収"], excerpt: "配管工・空調設備工・ガス配管工の年収を比較。管工事施工管理技士の効果も解説。" },
  { slug: "high-place-work-license", title: "高所作業車運転技能講習の取り方と活用場面", category: "license", tags: ["高所作業車","資格"], excerpt: "高所作業車の運転資格の種類、講習内容、費用。どんな現場で使うかを具体例で紹介。" },
  { slug: "construction-hierarchy-explained", title: "建設現場の職制 — 職長・班長・作業員の役割", category: "industry", tags: ["組織","現場管理"], excerpt: "建設現場の組織構造。職長・班長・作業員それぞれの役割と責任範囲を解説。" },
  { slug: "road-paving-work-guide", title: "舗装工事の仕事内容 — アスファルト・コンクリート", category: "job-type", tags: ["舗装","土木"], excerpt: "道路舗装工事の種類と作業の流れ。必要な重機の操作資格と年収の目安。" },
  { slug: "construction-independent-guide", title: "建設業で独立する方法 — 一人親方から法人化まで", category: "career", tags: ["独立","一人親方"], excerpt: "一人親方として独立する手順、必要な届出、法人化のタイミングを経験者が解説。" },
  { slug: "building-inspector-license", title: "建築物環境衛生管理技術者の資格と仕事", category: "license", tags: ["ビル管理","資格"], excerpt: "通称「ビル管」の資格概要、受験資格、試験内容、取得後のキャリアを解説。" },
  { slug: "construction-rain-day-work", title: "雨の日の建設現場 — 中止基準と待機時の給与", category: "industry", tags: ["雨天","労働条件"], excerpt: "雨天時の作業中止基準、待機中の給与支払い、室内作業への切り替えについて。" },

  // === 5月: スキルアップ月間 ===
  { slug: "construction-skill-sheet", title: "建設業界のスキルマップ — 自分のレベルを把握する", category: "career", tags: ["スキル","自己分析"], excerpt: "技術力・資格・経験年数を可視化するスキルマップの作り方。転職や昇給交渉にも活用。" },
  { slug: "excavation-work-guide", title: "掘削工事の種類と安全管理 — 基礎知識", category: "job-type", tags: ["掘削","安全"], excerpt: "根切り・開削・推進工法など掘削工事の種類。土留め工法と安全管理のポイント。" },
  { slug: "construction-cad-operator", title: "建設業界のCADオペレーター — 仕事内容と年収", category: "job-type", tags: ["CAD","設計"], excerpt: "建設現場で使われるCADの種類、オペレーターの仕事内容、年収、在宅ワークの可能性。" },
  { slug: "management-license-comparison", title: "施工管理技士6種類を比較 — どれを取るべき？", category: "license", tags: ["施工管理技士","比較"], excerpt: "建築・土木・電気・管・造園・建設機械の施工管理技士6種を難易度・需要・年収で比較。" },
  { slug: "construction-training-cost", title: "建設系資格の取得費用一覧 — 会社負担はどこまで？", category: "salary", tags: ["資格費用","福利厚生"], excerpt: "主要な建設系資格の受験料・講習費用一覧。会社の資格取得支援制度の実態。" },
  { slug: "interview-sekokan-5years", title: "施工管理5年目のキャリアと年収の変化", category: "interview", tags: ["施工管理","キャリア"], excerpt: "施工管理技士として5年目を迎えた29歳のリアル。年収の推移とこれからの目標。" },
  { slug: "construction-bim-basics", title: "BIMとは何か — 建設業界のデジタル化入門", category: "industry", tags: ["BIM","ICT"], excerpt: "BIM（Building Information Modeling）の基本概念と建設現場での活用事例を初心者向けに解説。" },
  { slug: "steel-frame-worker-guide", title: "鉄骨工の仕事内容と年収 — 高所作業のプロ", category: "job-type", tags: ["鉄骨","職種解説"], excerpt: "鉄骨建方・溶接・ボルト締めなど鉄骨工の仕事内容、必要な資格、年収を紹介。" },
  { slug: "construction-benefit-comparison", title: "建設会社の福利厚生比較 — 確認すべき10項目", category: "salary", tags: ["福利厚生","比較"], excerpt: "社会保険・退職金・資格手当・寮など、入社前に確認すべき福利厚生10項目。" },
  { slug: "organic-solvent-license", title: "有機溶剤作業主任者の資格 — 取得方法と必要な現場", category: "license", tags: ["有機溶剤","安全資格"], excerpt: "有機溶剤作業主任者技能講習の概要。塗装・防水工事で必要な場面を解説。" },
  { slug: "construction-subcontractor-guide", title: "建設業の元請と下請の関係 — 仕組みと注意点", category: "industry", tags: ["元請","下請"], excerpt: "建設業界の重層下請構造の仕組み。元請・一次下請・二次下請の関係と注意すべき点。" },
  { slug: "tunnel-work-guide", title: "トンネル工事の仕事内容 — 山岳工法とシールド工法", category: "job-type", tags: ["トンネル","土木"], excerpt: "トンネル工事の2大工法と作業内容。特殊な資格、給与、勤務形態を解説。" },
  { slug: "construction-career-at-30", title: "30代から建設業界へ転職 — 未経験でも遅くない理由", category: "career", tags: ["30代","転職"], excerpt: "30代で建設業界に転職するメリットとデメリット。成功のポイントを経験者が解説。" },
  { slug: "construction-night-salary-premium", title: "建設業の各種手当一覧 — 夜勤・危険・資格手当", category: "salary", tags: ["手当","給与"], excerpt: "夜勤手当・危険手当・資格手当・現場手当など建設業界の各種手当の相場。" },
  { slug: "small-construction-license", title: "小型移動式クレーン運転技能講習 — 取得ガイド", category: "license", tags: ["クレーン","資格"], excerpt: "小型移動式クレーン（つり上げ荷重5t未満）の運転技能講習。日数・費用・試験内容。" },
  { slug: "interview-couple-construction", title: "夫婦で建設業界 — 内装工事の家族経営の現実", category: "interview", tags: ["家族経営","内装"], excerpt: "夫婦でクロス貼りの仕事をしている40代の体験談。家族経営のメリットと難しさ。" },

  // === 6月: 梅雨・安全対策 ===
  { slug: "construction-rainy-season-safety", title: "梅雨時期の建設現場 — 安全対策と工程管理", category: "industry", tags: ["梅雨","安全対策"], excerpt: "梅雨時期の建設現場で注意すべき安全対策。足元の滑り防止、電気設備の漏電対策など。" },
  { slug: "construction-moisture-measures", title: "雨天時のコンクリート打設 — 品質管理のポイント", category: "industry", tags: ["コンクリート","品質管理"], excerpt: "雨天時のコンクリート打設は可能か。養生方法と品質を確保するための管理ポイント。" },
  { slug: "drainage-work-guide", title: "排水設備工事の仕事内容と必要な資格", category: "job-type", tags: ["排水","設備"], excerpt: "排水設備工事の種類、仕事内容、排水設備工事責任技術者の資格について解説。" },
  { slug: "construction-insurance-guide", title: "建設業の労災保険 — 補償内容と申請手続き", category: "industry", tags: ["労災","保険"], excerpt: "建設現場での労災事故。補償の内容、申請の流れ、一人親方の特別加入について。" },
  { slug: "scaffolding-safety-rules", title: "足場作業の安全ルール — 法改正のポイント", category: "license", tags: ["足場","安全法規"], excerpt: "足場作業に関する労働安全衛生法の最新改正ポイント。特別教育の義務化と内容。" },
  { slug: "construction-drone-survey", title: "ドローン測量の基本 — 建設業界での活用と資格", category: "industry", tags: ["ドローン","測量"], excerpt: "建設現場でのドローン活用事例。測量・点検での使い方と操縦に必要な資格。" },
  { slug: "interview-50s-construction", title: "50代で建設業界に転職 — セカンドキャリアの選択", category: "interview", tags: ["50代","転職体験"], excerpt: "50代で警備員から建設作業員に転職した男性の体験。体力面の工夫と収入の変化。" },
  { slug: "demolition-license-guide", title: "解体工事施工技士の資格 — 取得方法と活用", category: "license", tags: ["解体","資格"], excerpt: "解体工事施工技士の受験資格、試験内容、合格率。解体業界でのキャリアアップに。" },
  { slug: "electrical-work-salary-up", title: "電気工事士が年収を上げる方法 — 資格と転職", category: "salary", tags: ["電気工事士","年収アップ"], excerpt: "電気工事士が年収を上げるための方法。上位資格の取得、転職先の選び方。" },
  { slug: "construction-document-management", title: "施工管理の書類業務 — 効率化の方法", category: "career", tags: ["書類","施工管理"], excerpt: "施工管理技士の書類業務の内容。日報・写真管理・安全書類の効率化ツールを紹介。" },
  { slug: "formwork-carpenter-guide", title: "型枠大工の仕事と年収 — RC造のスペシャリスト", category: "job-type", tags: ["型枠","職種解説"], excerpt: "型枠大工の仕事内容、使う道具、年収相場。未経験からの技術習得期間を解説。" },
  { slug: "construction-ai-future", title: "AIは建設業界をどう変える？ — 自動化の現状と将来", category: "industry", tags: ["AI","ICT"], excerpt: "建設ロボット・AIによる施工管理支援など、建設業界のAI活用の現状と将来展望。" },
  { slug: "construction-education-training", title: "建設業界の職業訓練校 — 入校方法と学べること", category: "career", tags: ["職業訓練","教育"], excerpt: "ポリテクセンター等の職業訓練校で建設技術を学ぶ方法。入校条件・期間・費用。" },
  { slug: "construction-heatstroke-law", title: "建設現場の暑さ対策義務 — 法令で求められること", category: "industry", tags: ["暑さ対策","法規"], excerpt: "WBGT値の管理義務、休憩場所の設置基準など、建設現場の暑さ対策に関する法令。" },

  // === 7月: 夏場の現場・熱中症対策 ===
  { slug: "construction-heatstroke-prevention", title: "建設現場の熱中症対策 — 予防と応急処置", category: "industry", tags: ["熱中症","安全"], excerpt: "建設現場での熱中症を防ぐための対策。水分補給・塩分摂取・空調服の活用法。" },
  { slug: "cooling-vest-guide", title: "空調服・冷却ベストの選び方 — 現場別おすすめ", category: "industry", tags: ["空調服","暑さ対策"], excerpt: "ファン付き作業着・冷却ベストの種類と選び方。建築・土木・内装の現場別おすすめ。" },
  { slug: "summer-construction-schedule", title: "夏場の建設現場 — 作業時間と休憩のルール", category: "industry", tags: ["夏場","作業時間"], excerpt: "夏の建設現場での早朝シフト・昼休み延長など、暑さ対策としての作業時間の工夫。" },
  { slug: "bridge-construction-work", title: "橋梁工事の仕事内容と必要な資格", category: "job-type", tags: ["橋梁","土木"], excerpt: "橋梁の新設・補修工事の流れ。必要な資格と経験、特有の危険と安全管理。" },
  { slug: "construction-summer-salary", title: "建設業界の夏季手当と暑中手当 — 支給する企業は？", category: "salary", tags: ["夏季手当","待遇"], excerpt: "暑中手当・夏季特別手当を支給する建設会社の割合と支給額の目安。" },
  { slug: "gas-welding-license", title: "ガス溶接技能講習の取り方 — 費用と日数", category: "license", tags: ["ガス溶接","資格"], excerpt: "ガス溶接技能講習の概要。アーク溶接との違い、受講資格、費用を解説。" },
  { slug: "interview-sekokan-career-up", title: "現場作業員から施工管理へ — 10年の軌跡", category: "interview", tags: ["キャリアアップ","施工管理"], excerpt: "建設作業員から施工管理技士にキャリアアップした38歳の10年間の成長記録。" },
  { slug: "construction-uv-protection", title: "建設作業員のUV対策 — 日焼け止めと装備", category: "industry", tags: ["紫外線","健康"], excerpt: "屋外作業での紫外線対策。日焼け止めの塗り方、長袖作業着、サングラスの選び方。" },
  { slug: "plant-engineering-guide", title: "プラント建設の仕事内容と年収 — 高待遇の理由", category: "job-type", tags: ["プラント","職種解説"], excerpt: "化学プラント・発電所の建設工事の仕事内容。高待遇の理由と求められる資格。" },
  { slug: "construction-hydration-tips", title: "建設現場の水分補給 — 正しい飲み方と経口補水液", category: "industry", tags: ["水分補給","健康"], excerpt: "現場作業中の正しい水分補給の量とタイミング。経口補水液とスポーツドリンクの違い。" },
  { slug: "operation-chief-license", title: "作業主任者の資格一覧 — 建設現場で必要な13種", category: "license", tags: ["作業主任者","資格一覧"], excerpt: "建設現場で必要な作業主任者の資格13種類。取得の優先順位と講習内容を解説。" },
  { slug: "construction-efficiency-tools", title: "建設現場の効率化ツール — ICT施工の実践例", category: "industry", tags: ["ICT","効率化"], excerpt: "i-Construction推進で導入が進むICTツール。現場での活用事例と効果を紹介。" },
  { slug: "construction-career-at-40", title: "40代の建設業界転職 — 経験を活かすポジション", category: "career", tags: ["40代","転職"], excerpt: "40代で建設業界に転職する際の狙い目ポジション。管理職・施工管理・安全管理。" },
  { slug: "asbestos-removal-work", title: "アスベスト除去工事の仕事と資格", category: "job-type", tags: ["アスベスト","解体"], excerpt: "アスベスト除去工事の流れ、必要な資格（石綿作業主任者）、安全管理の重要性。" },
  { slug: "construction-part-time-salary", title: "建設業のアルバイト・日雇い — 日当相場と探し方", category: "salary", tags: ["アルバイト","日雇い"], excerpt: "建設現場のアルバイト・日雇いの日当相場、探し方、正社員との待遇の違い。" },
  { slug: "energy-management-license", title: "エネルギー管理士の資格 — 建設業での活用", category: "license", tags: ["エネルギー管理","資格"], excerpt: "エネルギー管理士の試験概要と建設・設備業界での活用場面。省エネ法との関連。" },
  { slug: "interview-foreign-worker-japan", title: "外国人技能実習生の建設現場 — 共に働く日本人の声", category: "interview", tags: ["外国人","多様性"], excerpt: "外国人技能実習生と一緒に働く日本人作業員が語る、コミュニケーションの工夫と課題。" },
  { slug: "construction-summer-work-tips", title: "夏の建設現場を乗り切る10のコツ", category: "industry", tags: ["夏場","健康"], excerpt: "現場経験者が教える夏場の建設作業を乗り切るための実践的な10のアドバイス。" },
  { slug: "reinforced-concrete-basics", title: "鉄筋コンクリート造（RC造）の基礎知識", category: "industry", tags: ["RC造","基礎知識"], excerpt: "RC造の仕組み、施工の流れ、関わる職種を建設初心者向けにわかりやすく解説。" },
  { slug: "construction-retirement-planning", title: "建設業界の退職後のキャリア — 経験を活かす仕事", category: "career", tags: ["退職後","シニア"], excerpt: "建設業界を退職した後のキャリア選択肢。技術指導員・安全コンサルタント・講師の道。" },

  // === 7月後半〜追加記事 ===
  { slug: "construction-fire-prevention", title: "建設現場の火災予防 — 溶接・溶断作業の注意点", category: "industry", tags: ["火災予防","安全"], excerpt: "溶接・溶断作業中の火災事故を防ぐための対策。養生方法と消火器の配置基準。" },
  { slug: "pile-driving-work", title: "杭打ち工事の種類と仕事内容", category: "job-type", tags: ["杭工事","基礎"], excerpt: "既製杭・場所打ち杭の違い、施工の流れ、従事するための資格と年収を解説。" },
  { slug: "construction-commuting-allowance", title: "建設会社の通勤手当 — 車通勤・電車通勤の支給額", category: "salary", tags: ["通勤手当","待遇"], excerpt: "建設会社の通勤手当の支給基準。車通勤のガソリン代・駐車場代の扱いについて。" },
  { slug: "construction-permit-types", title: "建設業許可の種類 — 29業種の分類と取得要件", category: "industry", tags: ["建設業許可","法規"], excerpt: "建設業許可の一般と特定の違い、29業種の分類、取得に必要な経営業務管理責任者の要件。" },
  { slug: "land-surveyor-career", title: "測量士のキャリアパス — 独立までの道筋", category: "career", tags: ["測量","キャリア"], excerpt: "測量士としてのキャリアパス。会社員から独立開業するまでに必要な経験と手続き。" },
  { slug: "interview-retired-to-security", title: "建設作業員から施設警備へ — 60代の転身", category: "interview", tags: ["シニア","転職体験"], excerpt: "60代で建設作業員を引退し、施設警備に転職した男性の体験談。体力の変化と新しいやりがい。" },
  { slug: "construction-night-shift-health", title: "夜勤続きの建設作業員の健康管理術", category: "industry", tags: ["夜勤","健康"], excerpt: "夜間工事が続くときの睡眠・食事・体調管理のコツ。現場経験者のアドバイス。" },
  { slug: "signboard-installer-guide", title: "看板工事・サイン工事の仕事と資格", category: "job-type", tags: ["看板","特殊工事"], excerpt: "看板・サインの設置工事の仕事内容。高所作業車の資格や電気工事士との関連。" },
  { slug: "construction-2024-regulation", title: "2024年問題のその後 — 建設業界の残業規制2年目", category: "industry", tags: ["法規制","働き方改革"], excerpt: "2024年施行の残業上限規制から2年。建設業界の対応状況と現場への影響を検証。" },
  { slug: "first-class-pipe-management", title: "1級管工事施工管理技士の受験対策", category: "license", tags: ["管工事","施工管理技士"], excerpt: "1級管工事施工管理技士の試験概要、出題傾向、合格者の勉強法を紹介。" },
  { slug: "construction-salary-vs-office", title: "建設業界とオフィスワークの年収比較", category: "salary", tags: ["年収比較","他業界"], excerpt: "建設業界の年収をIT・製造・サービス業と比較。体力仕事のプレミアムは存在するか。" },
  { slug: "waterworks-engineer-license", title: "給水装置工事主任技術者の資格ガイド", category: "license", tags: ["給水","資格"], excerpt: "給水装置工事主任技術者の受験資格、試験内容、合格率。配管工のキャリアアップに。" },
  { slug: "construction-remote-management", title: "遠隔施工管理の現状 — ウェアラブルカメラの活用", category: "industry", tags: ["遠隔","ICT"], excerpt: "ウェアラブルカメラ・タブレットを使った遠隔施工管理の導入事例と課題。" },
  { slug: "construction-hearing-protection", title: "建設現場の騒音対策 — 難聴予防と保護具", category: "industry", tags: ["騒音","安全"], excerpt: "建設現場での騒音性難聴を防ぐための耳栓・イヤーマフの選び方と使用義務。" },
  { slug: "interview-sekokan-to-developer", title: "施工管理からデベロッパーへ — 発注者側への転職", category: "interview", tags: ["デベロッパー","転職体験"], excerpt: "ゼネコンの施工管理からデベロッパーに転職した33歳の体験談。働き方の変化と年収。" },
  { slug: "solar-panel-installer-guide", title: "太陽光パネル設置工事の仕事と将来性", category: "job-type", tags: ["太陽光","再エネ"], excerpt: "太陽光パネル設置工事の需要、仕事内容、必要な資格。再生可能エネルギー市場の展望。" },
  { slug: "construction-volunteer-disaster", title: "建設業者の災害復旧活動 — 社会貢献と課題", category: "industry", tags: ["災害","社会貢献"], excerpt: "地震・台風の際の建設業者による災害復旧活動。社会的役割と人手不足の課題。" },
  { slug: "construction-foreign-worker-system", title: "建設業の外国人材受入れ制度 — 技能実習と特定技能", category: "industry", tags: ["外国人材","制度"], excerpt: "建設分野の技能実習と特定技能の違い。受入れ企業の要件と手続きの流れ。" },
  { slug: "site-supervisor-daily-routine", title: "施工管理技士の1日 — 朝礼から日報まで", category: "career", tags: ["施工管理","1日の流れ"], excerpt: "施工管理技士の典型的な1日のスケジュール。朝礼・巡回・打合せ・書類作業の時間配分。" },
  { slug: "construction-loan-support", title: "建設業界の住宅ローン審査 — 日給月給でも通る？", category: "salary", tags: ["住宅ローン","生活"], excerpt: "建設作業員の住宅ローン審査の実態。日給月給制・一人親方でも審査を通すコツ。" },
  { slug: "hazardous-material-license", title: "危険物取扱者の資格 — 建設現場での活用場面", category: "license", tags: ["危険物","資格"], excerpt: "危険物取扱者（乙種4類）の概要と、建設現場での燃料管理や塗装作業での活用。" },
  { slug: "construction-promotion-path", title: "建設会社の昇進・昇格の仕組み — 評価基準は？", category: "career", tags: ["昇進","評価"], excerpt: "建設会社の昇進制度の実態。資格・経験年数・人望など評価されるポイントを解説。" },
  { slug: "interview-intern-to-fulltime", title: "インターンから正社員へ — 建設会社での学生時代の経験", category: "interview", tags: ["インターン","学生"], excerpt: "大学生時代に建設会社でインターンを経験し、そのまま正社員になった24歳の話。" },
  { slug: "construction-earthquake-resistant", title: "耐震工事の仕事内容 — 需要が伸びる専門分野", category: "job-type", tags: ["耐震","リフォーム"], excerpt: "耐震補強工事の種類と仕事内容。古い建物の耐震化需要の拡大と求められる技術。" },
  { slug: "construction-green-building", title: "グリーンビルディングと建設業 — 環境配慮型建築の仕事", category: "industry", tags: ["環境","ZEB"], excerpt: "ZEB・LEED認証など環境配慮型建築の動向。建設業界の新しい仕事の領域。" },
  { slug: "building-equipment-inspector", title: "建築設備検査員の資格と仕事", category: "license", tags: ["検査","資格"], excerpt: "建築設備検査員の資格概要、講習内容、定期検査の仕事内容を解説。" },
  { slug: "construction-work-life-balance", title: "建設業界のワークライフバランス — 改善する企業の取組み", category: "industry", tags: ["ワークライフバランス","働き方"], excerpt: "週休2日制の導入・ICT活用・業務効率化など、建設業界のWLB改善の取組み事例。" },
  { slug: "construction-network-building", title: "建設業界の人脈作り — 仕事につながるネットワーク", category: "career", tags: ["人脈","キャリア"], excerpt: "建設業界での人脈の作り方と重要性。勉強会・組合・SNSの活用法。" },
  { slug: "prefab-construction-guide", title: "プレハブ建築の仕事内容 — 工場生産と現場組立", category: "job-type", tags: ["プレハブ","建築"], excerpt: "プレハブ工法の特徴と現場での組立作業の流れ。必要な技術と求人の探し方。" },
  { slug: "construction-inheritance-business", title: "建設会社の事業承継 — 後継者不足の現状と対策", category: "industry", tags: ["事業承継","経営"], excerpt: "中小建設会社の事業承継問題。後継者候補の育成と社外承継（M&A）の選択肢。" },
  { slug: "interview-comeback-construction", title: "建設業界に出戻り転職 — 他業種を経験して戻った理由", category: "interview", tags: ["出戻り","転職体験"], excerpt: "一度IT業界に転職したが建設現場に戻った36歳の体験談。他業界で気づいた建設業の魅力。" },
  { slug: "construction-quality-control", title: "建設現場の品質管理 — 検査の種類と合否基準", category: "industry", tags: ["品質管理","検査"], excerpt: "配筋検査・コンクリート強度試験・出来形検査など、建設現場の品質管理体制を解説。" },
  { slug: "construction-job-matching-tips", title: "建設業界の求人 — 自分に合った会社を見つける方法", category: "career", tags: ["求人","転職"], excerpt: "建設会社を選ぶ際のチェックポイント。会社規模・現場エリア・待遇の見方を解説。" },
  { slug: "construction-generation-gap", title: "建設現場の世代間ギャップ — ベテランと若手の橋渡し", category: "industry", tags: ["世代間","コミュニケーション"], excerpt: "建設現場でのベテランと若手のコミュニケーション課題と、円滑に働くためのポイント。" },
  { slug: "construction-overseas-work", title: "海外の建設現場で働く — 日本人技術者の需要", category: "career", tags: ["海外","キャリア"], excerpt: "東南アジア・中東などで活躍する日本人建設技術者の需要。給与水準と必要なスキル。" },
  { slug: "construction-future-2030", title: "2030年の建設業界 — 技術革新と人材の未来予測", category: "industry", tags: ["将来","技術革新"], excerpt: "ロボット施工・3Dプリンティング建築・完全BIM化など、2030年に向けた建設業界の変化を展望。" },
  { slug: "construction-first-license-success", title: "建設系の資格を初めて取得した日 — 合格者の声", category: "interview", tags: ["資格合格","体験談"], excerpt: "建設系の資格に初めて合格した人たちの声を集めました。勉強のコツと合格後の変化。" },
  { slug: "construction-gratitude-message", title: "建設業界で働くすべての人へ — 私たちが街をつくる", category: "industry", tags: ["やりがい","社会貢献"], excerpt: "建設業界で働くことの意義と誇り。インフラ・住宅・施設を支える仕事のやりがいを伝えます。" },

  // === 追加記事: 200到達分 ===
  { slug: "construction-renovation-market", title: "リフォーム・リノベーション市場 — 建設業の成長分野", category: "industry", tags: ["リフォーム","市場"], excerpt: "新築からリフォームへ。リノベーション市場の拡大と、必要とされる技術・資格。" },
  { slug: "crane-signal-operator", title: "クレーン合図者の資格と役割 — 安全な揚重作業のために", category: "license", tags: ["クレーン","安全"], excerpt: "クレーン合図者の特別教育の内容と、現場での合図方法。吊り荷作業の安全を守る重要な役割。" },
  { slug: "concrete-pump-operator", title: "コンクリートポンプ車の運転 — 必要な資格と仕事", category: "job-type", tags: ["コンクリート","オペレーター"], excerpt: "コンクリートポンプ車の運転に必要な資格、仕事内容、年収の目安を解説。" },
  { slug: "construction-mentor-importance", title: "建設現場での良い師匠の見つけ方", category: "career", tags: ["師匠","成長"], excerpt: "技術を学ぶ上で重要な師匠との出会い。良い指導者を見つけるためのポイントと心構え。" },
  { slug: "construction-startup-cost", title: "建設業で独立する際の初期費用 — 資金計画ガイド", category: "salary", tags: ["独立","資金"], excerpt: "一人親方・法人設立に必要な初期費用の目安。工具・車両・保険・許認可の費用一覧。" },
  { slug: "interview-father-son-construction", title: "親子で建設会社を営む — 2代目の苦悩と覚悟", category: "interview", tags: ["事業承継","家族"], excerpt: "父から建設会社を引き継いだ2代目社長の体験談。経営と現場の両立の難しさ。" },
  { slug: "scaffolding-inspection-rules", title: "足場の点検義務 — 組立後・強風後の確認事項", category: "industry", tags: ["足場","点検"], excerpt: "足場の設置後・強風後に義務付けられている点検項目と、記録の残し方を解説。" },
  { slug: "construction-dust-measures", title: "建設現場の粉じん対策 — 防塵マスクの選び方", category: "industry", tags: ["粉じん","安全"], excerpt: "建設現場で発生する粉じんの種類と健康への影響。防塵マスクの種類と正しい装着法。" },
  { slug: "electrical-panel-installer", title: "分電盤・配電盤の設置工事 — 専門性の高い電気工事", category: "job-type", tags: ["電気","配電盤"], excerpt: "分電盤・配電盤の設置工事に携わる電気工事士の仕事内容と求められる技術レベル。" },
  { slug: "construction-camp-life", title: "建設現場の宿舎・寮生活 — リアルな住環境", category: "industry", tags: ["寮","生活"], excerpt: "建設会社の寮や現場宿舎のリアルな住環境。間取り・設備・費用・ルールについて。" },
  { slug: "second-class-pipe-management", title: "2級管工事施工管理技士の受験対策", category: "license", tags: ["管工事","2級"], excerpt: "2級管工事施工管理技士の受験資格、試験科目、おすすめの勉強スケジュールを紹介。" },
  { slug: "construction-daily-report-tips", title: "施工管理の日報の書き方 — 効率的な記録方法", category: "career", tags: ["日報","施工管理"], excerpt: "施工管理技士の日報に何を書くべきか。効率的な記録方法とデジタルツールの活用。" },
  { slug: "interview-young-entrepreneur", title: "25歳で建設会社を起業 — 若手経営者の挑戦", category: "interview", tags: ["起業","若手"], excerpt: "25歳で内装工事会社を起業した若手経営者のインタビュー。独立のきっかけと経営の現実。" },
  { slug: "construction-earthquake-response", title: "地震発生時の建設現場の対応 — 避難と安全確認", category: "industry", tags: ["地震","安全"], excerpt: "建設現場で地震が発生した際の避難手順、安全確認の方法、BCP対応について。" },
  { slug: "flooring-installer-guide", title: "床仕上げ工の仕事と年収 — フローリング・タイル・長尺", category: "job-type", tags: ["床","内装"], excerpt: "フローリング・塩ビタイル・長尺シートなど床仕上げ工の仕事内容と年収。" },
  { slug: "construction-certification-merit", title: "建設業界の資格 — 取得で年収はどれだけ上がる？", category: "salary", tags: ["資格","年収アップ"], excerpt: "主要な建設系資格ごとの年収上昇額を調査。投資対効果の高い資格ランキング。" },
  { slug: "landscape-construction-guide", title: "造園工事の仕事内容 — 緑を作るプロフェッショナル", category: "job-type", tags: ["造園","職種解説"], excerpt: "公園・庭園・屋上緑化などの造園工事の仕事内容。造園施工管理技士の資格も解説。" },
  { slug: "construction-blackout-measures", title: "建設現場の停電対策 — 発電機の種類と安全な使い方", category: "industry", tags: ["停電","安全"], excerpt: "工事用発電機の種類と使い方。感電防止・CO中毒防止の注意点。" },
  { slug: "construction-body-maintenance", title: "建設作業員の体のケア — 腰痛・膝痛の予防法", category: "industry", tags: ["健康","体のケア"], excerpt: "建設作業員に多い腰痛・膝痛の原因と予防法。ストレッチ・サポーター・整体の活用。" },
  { slug: "boiler-engineer-license", title: "ボイラー技士の資格 — 建設設備業での需要", category: "license", tags: ["ボイラー","資格"], excerpt: "ボイラー技士（特級・1級・2級）の資格概要と建設設備業界での活用場面。" },
  { slug: "construction-innovation-startups", title: "建設テック企業の台頭 — スタートアップが変える業界", category: "industry", tags: ["スタートアップ","技術革新"], excerpt: "建設テック分野のスタートアップ企業の動向。業務効率化・安全管理・マッチングの革新。" },
  { slug: "construction-pride-stories", title: "建設業界で誇れる瞬間 — 現場職人たちの声", category: "interview", tags: ["やりがい","インタビュー"], excerpt: "建設業界で働く人たちが最も誇りに感じた瞬間を集めました。竣工時の感動やお客様の声。" },
  { slug: "construction-transfer-checklist", title: "建設業界への転職チェックリスト — 準備から入社まで", category: "career", tags: ["転職","チェックリスト"], excerpt: "建設業界への転職に必要な準備をチェックリスト形式で整理。漏れなく転職活動を進めるために。" },
  { slug: "paint-specialist-license", title: "塗装技能士の資格 — 1級・2級の違いと取得方法", category: "license", tags: ["塗装","技能士"], excerpt: "塗装技能士の受験資格、実技試験の内容、合格後の仕事の広がりを解説。" },
  { slug: "construction-team-building", title: "建設現場のチームワーク — 安全と品質を支える連携", category: "industry", tags: ["チームワーク","現場管理"], excerpt: "多職種が同時に働く建設現場でのチームワークの重要性。朝礼・KY活動の意義。" },
  { slug: "construction-career-summary-2026", title: "2026年上半期の建設業界振り返り — 求人動向と今後", category: "industry", tags: ["振り返り","市場"], excerpt: "2026年上半期の建設業界の求人動向、賃金の変化、主要プロジェクトの状況を振り返り。" },

  // === 追加200記事 第1バッチ（2026/7/19〜） ===
  { slug: "construction-eye-protection", title: "建設現場の目の保護 — 保護メガネの選び方と使用義務", category: "industry", tags: ["目の保護","安全"], excerpt: "建設現場で発生する目の事故と、保護メガネの種類・選び方・使用義務について解説。" },
  { slug: "construction-foot-safety", title: "建設作業員の足元の安全 — 安全靴の種類と選び方", category: "industry", tags: ["安全靴","装備"], excerpt: "現場の足元を守る安全靴の種類、規格、選び方のポイントを職種別に解説。" },
  { slug: "construction-vibration-illness", title: "振動障害とは — 建設作業員が知るべき予防法", category: "industry", tags: ["振動障害","健康"], excerpt: "削岩機・ブレーカー作業で起こる振動障害の症状と予防法。労災認定の基準も紹介。" },
  { slug: "construction-skin-protection", title: "建設現場の皮膚トラブル対策 — 手荒れ・湿疹の予防", category: "industry", tags: ["皮膚","健康"], excerpt: "セメント・塗料等による皮膚トラブルの原因と予防。保護クリームと手袋の選び方。" },
  { slug: "construction-first-aid", title: "建設現場の応急処置 — 知っておくべき基本手順", category: "industry", tags: ["応急処置","安全"], excerpt: "切り傷・打撲・骨折・やけど等、建設現場で起こりうる事故への応急処置の基本。" },
  { slug: "construction-aed-training", title: "AEDの使い方 — 建設現場で命を救う知識", category: "industry", tags: ["AED","救命"], excerpt: "心肺停止時にAEDで命を救うための基本知識。建設現場でのAED設置と使用手順。" },
  { slug: "construction-typhoon-prep", title: "台風時の建設現場対策 — 事前準備と作業中止判断", category: "industry", tags: ["台風","安全対策"], excerpt: "台風接近時の現場養生、作業中止判断、資材の固定など、被害を最小限にする備え。" },
  { slug: "construction-lightning-safety", title: "雷発生時の建設現場対応 — 屋外作業の危険回避", category: "industry", tags: ["雷","安全"], excerpt: "雷注意報・警報時の建設現場の対応。高所作業・鉄骨作業の中止基準と避難方法。" },
  { slug: "construction-winter-safety-tips", title: "冬場の建設現場の安全対策 — 凍結・寒冷対策", category: "industry", tags: ["冬場","安全"], excerpt: "冬季の建設現場で注意すべき凍結路面・低体温症・機械トラブルへの対策を解説。" },
  { slug: "construction-night-site-safety", title: "夜間工事の安全対策 — 照明と交通誘導", category: "industry", tags: ["夜間工事","安全"], excerpt: "夜間工事特有の危険と対策。照明の設置基準、交通誘導員の配置、体調管理のコツ。" },
  { slug: "construction-heavy-load-lifting", title: "重量物運搬の安全ルール — 腰痛事故防止", category: "industry", tags: ["重量物","腰痛"], excerpt: "建設現場での重量物運搬の法的制限と、腰痛事故を防ぐ正しい運搬方法。" },
  { slug: "construction-electrical-safety", title: "建設現場の電気安全 — 感電事故の防止", category: "industry", tags: ["電気","感電"], excerpt: "建設現場で発生する感電事故の原因と対策。仮設電源・電動工具の安全な使い方。" },

  { slug: "curtain-wall-installer", title: "カーテンウォール工事の仕事内容 — 高層ビルの外装", category: "job-type", tags: ["カーテンウォール","外装"], excerpt: "高層ビルの外装を構成するカーテンウォール工事の仕事内容と必要な技術を紹介。" },
  { slug: "alc-panel-installer", title: "ALCパネル工事の専門職 — 軽量気泡コンクリート", category: "job-type", tags: ["ALC","パネル"], excerpt: "ALCパネルの取付工事の仕事内容と、必要な資格・技能・年収の目安を解説。" },
  { slug: "metal-roof-worker", title: "金属屋根工事の専門職 — 板金工の仕事", category: "job-type", tags: ["屋根","板金"], excerpt: "ガルバリウム鋼板・銅板など金属屋根工事を担う板金工の仕事内容と年収を紹介。" },
  { slug: "tile-setter-pro", title: "タイル工の仕事と年収 — 住宅から商業施設まで", category: "job-type", tags: ["タイル","職種解説"], excerpt: "タイル張り職人の仕事内容、タイル張り技能士の資格、年収相場を詳しく解説。" },
  { slug: "exterior-siding-worker", title: "サイディング工事の仕事内容 — 外壁の専門職", category: "job-type", tags: ["サイディング","外装"], excerpt: "サイディング（外壁材）の取付工事の流れと、必要な技術・資格・年収を紹介。" },
  { slug: "drywall-specialist", title: "乾式壁工事の専門職 — 軽量鉄骨下地組立", category: "job-type", tags: ["乾式壁","内装"], excerpt: "LGS（軽量鉄骨）下地とボードによる乾式壁工事の仕事内容と求められる技能。" },
  { slug: "concrete-finisher", title: "コンクリート仕上げ工の役割 — 美しい表面を作る", category: "job-type", tags: ["コンクリート","仕上げ"], excerpt: "コンクリート打設後の金ゴテ仕上げを担う仕上げ工の技術と年収を解説。" },
  { slug: "masonry-worker", title: "石工の仕事内容と技術 — 伝統から現代建築まで", category: "job-type", tags: ["石工","伝統技術"], excerpt: "墓石・石垣・石張り等の石工の仕事内容と、石材技能士の資格、独立の可能性を紹介。" },

  { slug: "architect-1st-class-study", title: "1級建築士の受験対策 — 合格までの勉強法", category: "license", tags: ["建築士","1級"], excerpt: "1級建築士試験の概要と合格者の勉強法。学科・設計製図それぞれの対策を解説。" },
  { slug: "architect-2nd-class-study", title: "2級建築士の受験対策 — 独学合格の道", category: "license", tags: ["建築士","2級"], excerpt: "2級建築士試験の受験資格・試験内容・独学での合格戦略を詳しく紹介。" },
  { slug: "wooden-architect", title: "木造建築士の資格と活用場面", category: "license", tags: ["木造建築士","資格"], excerpt: "木造建築士の試験概要と、木造住宅業界でのキャリア活用について解説。" },
  { slug: "land-house-investigator", title: "土地家屋調査士の仕事と資格", category: "license", tags: ["土地家屋調査士","資格"], excerpt: "不動産登記の専門家である土地家屋調査士の仕事内容、試験、独立開業について。" },
  { slug: "real-estate-broker-construction", title: "宅地建物取引士と建設業 — 資格の活かし方", category: "license", tags: ["宅建","キャリア"], excerpt: "宅建士の資格を建設業界でどう活かすか。ハウスメーカー・不動産部門での需要。" },
  { slug: "labor-safety-consultant", title: "労働安全コンサルタントの資格 — 取得とキャリア", category: "license", tags: ["安全","コンサル"], excerpt: "労働安全コンサルタントの試験内容、受験資格、独立開業への道を解説。" },
  { slug: "refrigeration-3rd-class", title: "第三種冷凍機械責任者の資格 — 取得ガイド", category: "license", tags: ["冷凍機械","資格"], excerpt: "冷凍空調設備の保安を担う第三種冷凍機械責任者の試験概要と勉強法。" },

  { slug: "construction-career-at-20s", title: "20代の建設業界キャリア戦略 — 成長の黄金期", category: "career", tags: ["20代","キャリア"], excerpt: "20代で建設業界でのキャリアを最大化するための資格取得・経験の積み方。" },
  { slug: "construction-technical-writing", title: "建設分野の技術ライターという道", category: "career", tags: ["技術ライター","キャリア"], excerpt: "建設業界経験を活かして技術ライターになる方法。副業・独立の選択肢も紹介。" },
  { slug: "construction-trainer-career", title: "建設技能講師の道 — 経験を教育に活かす", category: "career", tags: ["講師","教育"], excerpt: "職業訓練校や技能講習の講師として、現場経験を次世代に伝えるキャリア。" },
  { slug: "construction-inspector-career", title: "建設検査員としてのキャリア — 第三者検査機関", category: "career", tags: ["検査員","キャリア"], excerpt: "建設物の第三者検査員として独立した立場で活躍するキャリアパスを紹介。" },
  { slug: "construction-consultant-career", title: "建設コンサルタントへの転身 — 計画・設計の専門家", category: "career", tags: ["コンサル","キャリア"], excerpt: "建設業界で経験を積んだ後、建設コンサルタントとして独立する道を解説。" },
  { slug: "construction-resume-mistakes", title: "建設業履歴書のNG例 — 採用担当が見る落とし穴", category: "career", tags: ["履歴書","面接"], excerpt: "建設会社の採用担当者が挙げる履歴書のNG例と、印象を良くする書き方のコツ。" },

  { slug: "construction-salary-east-japan", title: "東日本の建設業年収事情 — 関東・東北・北海道", category: "salary", tags: ["年収","地域"], excerpt: "関東・東北・北海道エリアの建設業の年収相場を職種別に比較して解説。" },
  { slug: "construction-salary-west-japan", title: "西日本の建設業年収事情 — 関西・中国・四国", category: "salary", tags: ["年収","地域"], excerpt: "関西・中国・四国エリアの建設業の年収相場と地域特性を詳しく紹介。" },
  { slug: "construction-allowance-details", title: "建設業の手当詳細一覧 — 基本給以外の収入", category: "salary", tags: ["手当","給与"], excerpt: "建設業界の各種手当（資格・職長・危険・家族等）の相場と支給条件を徹底解説。" },
  { slug: "construction-savings-strategy", title: "建設作業員の貯蓄術 — 効率的な資産形成", category: "salary", tags: ["貯蓄","資産形成"], excerpt: "変動しやすい建設業の収入から確実に貯蓄するための家計管理と節約のコツ。" },

  { slug: "interview-female-dokata", title: "土木の現場で活躍する30代女性の話", category: "interview", tags: ["女性","土木"], excerpt: "土木現場で現場代理人として働く30代女性の体験談。職場環境の変化と仕事のやりがい。" },
  { slug: "interview-returnee-japan", title: "海外から帰国した建設技術者の話", category: "interview", tags: ["海外","帰国"], excerpt: "東南アジアで10年働き、日本に帰国した40代建設技術者のキャリアと気づき。" },
  { slug: "interview-young-sekokan-female", title: "25歳女性施工管理技士の1年目", category: "interview", tags: ["女性","若手"], excerpt: "大学卒業後すぐ施工管理技士として働き始めた25歳女性の1年目のリアル。" },

  // === 追加200記事 第2バッチ ===
  { slug: "construction-vr-training", title: "VRを活用した建設安全訓練の最前線", category: "industry", tags: ["VR","安全教育"], excerpt: "仮想現実技術を使った建設現場の安全訓練の事例。墜落・感電等の危険体験を安全に。" },
  { slug: "construction-ar-application", title: "AR技術の建設現場応用事例", category: "industry", tags: ["AR","ICT"], excerpt: "拡張現実（AR）を活用した建設現場の作業支援・施工管理の最新事例を紹介。" },
  { slug: "construction-iot-sensor", title: "IoTセンサーで変わる建設現場の管理", category: "industry", tags: ["IoT","ICT"], excerpt: "建設現場でのIoTセンサーの活用事例。温湿度・作業員の位置・機器の稼働状況管理。" },
  { slug: "construction-5g-application", title: "5G通信が変える建設業界", category: "industry", tags: ["5G","通信"], excerpt: "5G通信の高速・低遅延を活かした建設現場の活用事例。遠隔施工・リアルタイム管理。" },
  { slug: "construction-ai-image-inspection", title: "AI画像解析による品質検査の実例", category: "industry", tags: ["AI","品質管理"], excerpt: "AIカメラによる建設現場の品質検査の導入事例。コンクリート欠陥・配筋確認の自動化。" },
  { slug: "construction-digital-twin", title: "デジタルツインと建設DXの未来", category: "industry", tags: ["デジタルツイン","DX"], excerpt: "建物や現場をデジタル空間に再現するデジタルツイン技術。設計から維持管理まで活用。" },
  { slug: "construction-wearable-tech", title: "ウェアラブル技術で進化する現場", category: "industry", tags: ["ウェアラブル","ICT"], excerpt: "スマートウォッチ・バイタルセンサー等、ウェアラブル端末による現場管理の進化。" },
  { slug: "construction-smart-helmet", title: "スマートヘルメットの機能と導入効果", category: "industry", tags: ["スマートヘルメット","安全"], excerpt: "センサー・カメラ・通信機能を搭載したスマートヘルメットの機能と現場での効果。" },
  { slug: "construction-blockchain-application", title: "ブロックチェーンの建設業活用", category: "industry", tags: ["ブロックチェーン","DX"], excerpt: "建設業界でのブロックチェーン活用事例。材料トレーサビリティ・契約管理等の可能性。" },
  { slug: "construction-3d-printer-reality", title: "3Dプリンター建築の実用化現状", category: "industry", tags: ["3Dプリンター","新技術"], excerpt: "3Dプリンターで住宅を建てる技術の実用化状況。海外事例と日本での取組み。" },
  { slug: "construction-cloud-services", title: "建設業クラウドサービスの選び方", category: "industry", tags: ["クラウド","ICT"], excerpt: "建設業向けクラウドサービスの種類と選び方。施工管理・図面管理・写真管理等。" },
  { slug: "construction-data-analytics", title: "建設データ分析で生産性向上", category: "industry", tags: ["データ分析","生産性"], excerpt: "建設現場のデータ分析による生産性向上の事例。工程・品質・安全の可視化。" },

  { slug: "elevator-installer", title: "エレベーター設置工事の仕事 — 昇降機業界の専門職", category: "job-type", tags: ["エレベーター","昇降機"], excerpt: "エレベーター設置工事の仕事内容と必要な資格。昇降機業界でのキャリアを解説。" },
  { slug: "escalator-installer", title: "エスカレーター設置工事の仕事 — 大型施設の専門職", category: "job-type", tags: ["エスカレーター","昇降機"], excerpt: "商業施設・駅等に設置するエスカレーターの据付工事の仕事と必要な技術。" },
  { slug: "hvac-installer", title: "空調設備工事の仕事内容 — 快適な環境を作る", category: "job-type", tags: ["空調","設備"], excerpt: "ビル・住宅の空調設備工事の仕事内容、必要な資格、年収相場を詳しく解説。" },
  { slug: "fire-alarm-installer", title: "自動火災報知設備工事の仕事 — 安全を守る専門職", category: "job-type", tags: ["火災報知","消防"], excerpt: "ビル・施設の火災報知設備の設置工事の仕事と、消防設備士の資格について。" },
  { slug: "sprinkler-installer", title: "スプリンクラー設備工事の仕事 — 消火設備のプロ", category: "job-type", tags: ["スプリンクラー","消火"], excerpt: "スプリンクラー等の消火設備の設置工事の流れ、必要な資格、年収を解説。" },
  { slug: "ev-charger-installer", title: "EV充電器設置工事の仕事 — 電気自動車時代の新職種", category: "job-type", tags: ["EV","電気"], excerpt: "電気自動車の充電器設置工事という新しい職種。必要な資格と将来性を紹介。" },
  { slug: "smart-home-integrator", title: "スマートホーム設備工事 — IoT時代の電気工事", category: "job-type", tags: ["スマートホーム","IoT"], excerpt: "スマートホーム設備の設置工事の仕事内容と、求められる電気・IT知識を解説。" },
  { slug: "security-system-installer", title: "セキュリティシステム設置工事の仕事", category: "job-type", tags: ["セキュリティ","設備"], excerpt: "防犯カメラ・入退室管理等のセキュリティ設備の設置工事の仕事内容と資格。" },

  { slug: "crane-derrick-1t", title: "クレーン・デリック運転士免許の取り方", category: "license", tags: ["クレーン","国家資格"], excerpt: "クレーン・デリック運転士免許の試験概要、受験資格、合格のポイントを解説。" },
  { slug: "tower-crane-operator", title: "タワークレーンオペレーターの資格と仕事", category: "license", tags: ["タワークレーン","資格"], excerpt: "高層建築で活躍するタワークレーンオペレーターに必要な資格と仕事内容。" },
  { slug: "hoist-operator-license", title: "巻上機運転特別教育の概要と取得方法", category: "license", tags: ["巻上機","特別教育"], excerpt: "ウインチ等の巻上機を運転するための特別教育の内容と受講方法を解説。" },
  { slug: "lift-operator-license", title: "リフト運転特別教育 — 建設用リフトの資格", category: "license", tags: ["リフト","特別教育"], excerpt: "建設現場で使用するリフトの運転に必要な特別教育の概要と活用場面を紹介。" },
  { slug: "power-shovel-license", title: "ドラグ・ショベル運転の特別教育", category: "license", tags: ["パワーショベル","特別教育"], excerpt: "小型のドラグ・ショベル運転に必要な特別教育の内容と、活用場面を解説。" },
  { slug: "bulldozer-license", title: "ブルドーザー運転特別教育の取得ガイド", category: "license", tags: ["ブルドーザー","特別教育"], excerpt: "ブルドーザー運転の特別教育の内容・日数・費用・活用場面を詳しく紹介。" },
  { slug: "road-roller-license", title: "ローラー運転特別教育 — 舗装工事の資格", category: "license", tags: ["ローラー","舗装"], excerpt: "舗装工事で使うロードローラーの運転に必要な特別教育の概要と取得方法。" },

  { slug: "construction-evaluator-career", title: "建築物評価士のキャリア — 既存建物の価値判定", category: "career", tags: ["評価士","キャリア"], excerpt: "建築物の価値を評価する建築物評価士のキャリア。不動産取引での需要と資格。" },
  { slug: "construction-interview-mistakes", title: "建設業面接のNG行動 — 採用担当が避ける人", category: "career", tags: ["面接","NG"], excerpt: "建設業の面接で避けるべきNG行動と、好印象を与える受け答えのポイント。" },
  { slug: "construction-portfolio-building", title: "施工実績の見せ方 — キャリアアップに活かす", category: "career", tags: ["実績","ポートフォリオ"], excerpt: "建設業でのキャリアアップに役立つ施工実績の整理と見せ方のコツを解説。" },
  { slug: "construction-recruitment-agent", title: "建設専門転職エージェントの活用法", category: "career", tags: ["エージェント","転職"], excerpt: "建設業界特化の転職エージェントの種類と活用方法。無料相談のメリット。" },
  { slug: "construction-from-restaurant", title: "飲食業から建設業への転職 — 成功のポイント", category: "career", tags: ["飲食業","転職"], excerpt: "飲食業界から建設業界へ転職する際のポイント。活かせるスキルと注意点。" },
  { slug: "construction-from-manufacturing", title: "製造業から建設業への転職 — 相性の良さ", category: "career", tags: ["製造業","転職"], excerpt: "製造業経験者が建設業界に転職する際の強みと活かせるスキルを解説。" },

  { slug: "construction-salary-kyushu", title: "九州地方の建設業年収事情 — 地域特性を解説", category: "salary", tags: ["年収","九州"], excerpt: "福岡・熊本・鹿児島等、九州の建設業年収相場と、地域特有のプロジェクトを紹介。" },
  { slug: "construction-salary-chubu", title: "中部地方の建設業年収 — 製造業集積地の特徴", category: "salary", tags: ["年収","中部"], excerpt: "愛知・静岡・新潟等、中部地方の建設業年収と、製造業関連の建設需要を解説。" },
  { slug: "construction-investment-basics", title: "建設業従事者の投資入門 — 資産運用の基本", category: "salary", tags: ["投資","資産運用"], excerpt: "建設業で働く方向けの投資の基本。リスクとリターン、始め方のステップ。" },
  { slug: "construction-nisa-ideco-guide", title: "NISA・iDeCoの活用法 — 建設業従事者の節税", category: "salary", tags: ["NISA","iDeCo"], excerpt: "建設業で働く方がNISA・iDeCoを活用して節税しながら資産形成する方法。" },

  { slug: "interview-plumber-life", title: "ベテラン配管工の人生 — 40年の経験を語る", category: "interview", tags: ["配管工","ベテラン"], excerpt: "配管工として40年以上働いてきた65歳ベテラン職人の人生と仕事への想い。" },
  { slug: "interview-glass-worker", title: "ガラス職人の仕事と誇り — 窓の向こうに見える街", category: "interview", tags: ["ガラス工","職人"], excerpt: "ビル・住宅のガラス工事を30年続けてきた職人が語る仕事の魅力と誇り。" },
  { slug: "interview-roofer-20years", title: "屋根職人20年の歩み — 空の近くで働く", category: "interview", tags: ["屋根","職人"], excerpt: "屋根工事一筋20年の42歳職人が語る、この仕事の魅力と大変さ。" },
]



